import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import AppIcon from "@/app/AppIcon";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <header className="flex items-center justify-between p-4 mx-auto container">
            <div className="left-side flex items-center space-x-4">
                <AppIcon className="w-8 h-8"/>
                <nav>
                    <ul className="flex space-x-4">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li>
                            <a href="/about">About</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div className="right-side">
                <nav>
                    <ul className="flex space-x-4">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li>
                            <a href="/about">About</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </header>
        {children}
        </body>
        </html>
    );
}
