# .github/workflows/deploy-github-pages.yaml

# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'develop' # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      # Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: List packages
        run: pnpm m ls --depth=-1
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          pnpm install
          pnpm --filter @material-tailwind-ui/* --filter=!@material-tailwind-ui/stories build

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install # default: npm install
          build_command: pnpm run storybook:build # default: npm run build-storybook
          path: stories/storybook-static # default: storybook-static
          checkout: false # default: true
