name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - feature/MTUI-57-website  # Deploy from this branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Manual Checkout
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: pnpm install -r

      - name: Build libraries first
        run: pnpm run packages:build

      - name: Build Next.js app
        run: pnpm run website:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
